version: '3.4'

services:
  within3weatherstation:
    image: within3weatherstation
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: ["node", "--inspect=0.0.0.0:3000", "index.js"]
