version: '3.4'

services:
  within3weatherstation:
    image: within3weatherstation
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    command: ["node", "--inspect=0.0.0.0:8080", "index.js"]
