version: '3.4'

services:
  within3weatherstation:
    image: within3weatherstation
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000
